### ISSUE TITLE
Failed to LOB Data: Error occurred in SQL Call Level Interface SQLSTATE=HY021 SQLCODE=-99999

### ISSUE THREAD

**Issue by sgonchigar** [kadler/python-ibmdb#12]
Hello, I didn't go thru all the way to know to create the ticket for IBMi related here.  sorry :(  Not sure if it can be moved. 

https://github.com/ibmdb/python-ibmdb/issues/900

**Comment by sgonchigar** [comment]
we are creating connection like this 
options = {
        db2.SQL_ATTR_TXN_ISOLATION: db2.SQL_TXN_NO_COMMIT,
        db2.SQL_ATTR_DBC_SYS_NAMING: db2.SQL_TRUE
    }
    conn = db2.connect(dsn=None, database='*LOCAL', user=None, password=None)
   conn.set_option(options)
   
   is there way to create the connection using ibm_db similar to above without explicitly mentioning the database,uid and pwd.

**Comment by kadler** [comment]
Why do you _want_ to use `ibm_db`? IMO, nobody should ever use that directly, but use ibm_db_dbi.

**Comment by kadler** [comment]
Besides, I don't think using ibm_db directly would solve your problem. There seems to be some problem in retrieving the LOB data.

**Comment by sgonchigar** [comment]
I see. Thank you,  was wondering if the stored proc call can be an execute_immediate() instead of cursor. IBM didn't find any issue with CLI trace, they have forwarded it to their developers.  When I use db2.connect(dsn=None, database='*LOCAL', user=None, password=None)  or db2.connect("DATABASE=*LOCAL"),  we get this error
 Additional Message Information             
 Job 806252/QUSER/QSQSRVR used for SQL server mode processing.       
 Error occurred in SQL Call Level Interface                
 Message ID . . . . . . :  SQ99999    Severity . . . . . . . :  30     
 Message type . . . . . :  Diagnostic                     
 Date sent . . . . . . :  11/17/23   Time sent . . . . . . :  10:54:48  
 Message . . . . :  Error occurred in SQL Call Level Interface         
 Cause . . . . . :  A procedure call encountered an error. The error code is 
  9. Error codes are:                             
   1 -- Memory allocation failure.                      
   2 -- Column number not valid.                       
   3 -- Program type out of range.                      
   4 -- SQL data type out of range.                      
   8 -- Operation canceled.                          
   9 -- Argument value not valid.                       
   10 -- Function sequence error.                       
   12 -- Transaction operation state not valid.                
  13 -- Memory management problem.         
IBM responded to ignore that message with this explanation:
That error can be ignored.  That happens when the db2 package you are using attempts to set an undefined connection attribute:
 [00003BF2:00000000000000B5][11-17-23 09:23:51.199824]
 ENTER: SQLSetConnectAttr
   SQLHDBC       2
   SQLINTEGER    7 (UNKNOWN)
   SQLPOINTER    8000000000000000000080169FFFDA08 (-1)
   SQLINTEGER    0
 [00003BF2:00000000000000B5][11-17-23 09:23:51.199936](0.000112)
 EXIT:  SQLSetConnectAttr with return code -1 (SQL_ERROR)
   SQLHDBC       2
   SQLINTEGER    7 (UNKNOWN)
   SQLPOINTER    8000000000000000000080169FFFDA08 (-1)
   SQLINTEGER    0
So the 7 (UNKNOWN) value is to set the concurrency mode but the value that this package is trying to set it to, -1, is undefined... 
The LOB issue is consistent, every time after 15,336 entries, it errors out.

**Comment by sgonchigar** [comment]
you can use the attached script to reproduce the error
[test_dataQ_example1.txt](https://github.com/kadler/python-ibmdb/files/13401503/test_dataQ_example1.txt)
CRTDTAQ DTAQ(YOURLIB/INPUTDQ)  MAXLEN(5000) SEQ(*KEYED)  KEYLEN(50) TEXT('Input Data Q') 
CRTDTAQ DTAQ(YOURLIB/OUTPUTDQ)  MAXLEN(5000) SEQ(*KEYED)  KEYLEN(50) TEXT('Input Data Q') 
SBMJOB CMD(STRQSH CMD('QIBM_MULTI_THREADED=Y;PATH=/QOpenSys/pkgs/bin:$PAT
H ;export PATH;python3 /home/sgonchigar/python/test_dataQ_example1.py "*LIBL" "INPUTDQ" "OUTPUTDQ" "KEY1" "50"')) JOB(PYDQJOB) JOBQ(<multi-thread JOBQ)                                                                       

expected output:
....................
2023-11-18 13:08:05,851 [INFO] outputStr = "15333"                                                     
2023-11-18 13:08:05,861 [INFO] waiting for next entry...                                               
2023-11-18 13:08:05,950 [INFO] outputStr = "15334"                                                     
2023-11-18 13:08:05,956 [INFO] waiting for next entry...                                               
2023-11-18 13:08:06,029 [INFO] outputStr = "15335"                                                     
2023-11-18 13:08:06,035 [INFO] waiting for next entry...                                               
2023-11-18 13:08:06,108 [INFO] outputStr = "15336"                                                     
2023-11-18 13:08:06,114 [INFO] waiting for next entry...                                               
--- Logging error ---                                                                                  
Traceback (most recent call last):                                                                     
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db_dbi.py", line 1472, in _fetch_helper         
    row = ibm_db.fetch_tuple(self.stmt_handler)                                                        
Exception: Failed to LOB Data: Error occurred in SQL Call Level Interface SQLSTATE=HY021 SQLCODE=-99999
During handling of the above exception, another exception occurred:                                    
Traceback (most recent call last):                                                                     
  File "/home/sgonchigar/python/test_dataQ_example1.py", line 151, in read_dataQ                       
    row = cur.fetchone()                                                                               
  File "/QOpenSys/pkgs/lib/python3.6/site-packages/ibm_db_dbi.py", line 1492, in fetchone              
    row_list = self._fetch_helper(1)

**Comment by kadler** [comment]
> IBM didn't find any issue with CLI trace, they have forwarded it to their developers

Did you open an ticket with IBM i support?

**Comment by sgonchigar** [comment]
Yes. Any alternatives that you can suggest to try while I am waiting?  IBM ticket - TS014755537

**Comment by kadler** [comment]
How big of an entry do you expect to receive from the data queue? If it can fit inside a VARCHAR, you could cast the output to a VARCHAR, eg.

```
        select CAST(MESSAGE_DATA as VARCHAR(5000) NOT NULL)
        from TABLE(QSYS2.RECEIVE_DATA_QUEUE(
                        DATA_QUEUE => '{inputKeyedDqName}',
                        DATA_QUEUE_LIBRARY => '{keyedDqLib}',
                        WAIT_TIME => -1,
                        KEY_ORDER => 'EQ',
                        KEY_DATA => cast('{dQKey}' as char({dQKeyLen}))
                        ))
```

Since your MAXLEN on the the example data queue is 5000, you can use VARCHAR(5000) here. If you have data queues with larger maximum sizes, adjust appropriately. If the max size is larger than the max of a non-null VARCHAR (32740), you will need to use CLOB though.

**Comment by sgonchigar** [comment]
Thank you, Thank you, Thank you!  Kevin. That worked. I tested with 20k,50k and 100k DQ entries.  The max size of the data is going to be 4000.  I do have some questions unrelated to this issue.  would you like me to open a new thread.    Appreciate your help.

**Comment by kadler** [comment]
Yeah, if the question is unrelated open a new issue.

**Comment by sgonchigar** [comment]
Thank you for the timely help.
