### ISSUE TITLE
cursor.rowcount is wrong (by about 32 bits)

### ISSUE THREAD

**Issue by jkyeung** [kadler/python-ibmdb#3]
Using the following packages as reported by `yum list`:
```
python3.ppc64                          3.6.8-1
python3-ibm_db.ppc64                   2.0.5.9-0
```
After updating some rows using cursor.execute, cursor.rowcount is not set to the actual number of affected rows, but rather `(actual_rows + 1) * 2**32 - 1`. I imagine this is due to some mix-up with respect to integer size in the C implementation.

**Comment by kadler** [comment]
This is a 64-bit issue caused by `SQLLEN` being defined as a `long` instead of an `int`/`SQLINTEGER`:

https://github.com/kadler/python-ibmdb/blob/ibmi/IBM_DB/ibm_db/ibm_db.h#L152
